[
    {
        "id": "1",
        "question": "Name the mandatory symbol.|à¤…à¤¨à¤¿à¤µà¤¾à¤°à¥à¤¯ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "option2": "Give way|à¤°à¤¾à¤¸à¥à¤¤à¤¾ à¤¦à¥‡à¤‚",
        "option3": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "correct_option": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/002.jpg"
    },
    {
        "id": "2",
        "question": "Name the warning sign.|à¤šà¥‡à¤¤à¤¾à¤µà¤¨à¥€ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "School|à¤¸à¥à¤•à¥‚à¤²",
        "option2": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option3": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Pedestrian crossing|à¤ªà¥ˆà¤¦à¤² à¤ªà¤¾à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¸à¥à¤¥à¤¾à¤¨",
        "correct_option": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/005.jpg"
    },
    {
        "id": "3",
        "question": "Which one is personal safety?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤¹à¥ˆ?",
        "option1": "Keep the machine clean|à¤®à¤¶à¥€à¤¨ à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option2": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "option3": "Keep the gangway and floor clean|à¤—à¥ˆà¤‚à¤—à¤µà¥‡ à¤”à¤° à¤«à¥à¤²à¥‹à¤° à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option4": "Keep the tools at their proper place|à¤‰à¤ªà¤•à¤°à¤£à¥‹à¤‚ à¤•à¥‹ à¤‰à¤¨à¤•à¥‡ à¤‰à¤šà¤¿à¤¤ à¤¸à¥à¤¥à¤¾à¤¨ à¤ªà¤° à¤°à¤–à¥‡à¤‚",
        "correct_option": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },

    {
        "id": "4",
        "question": "Flammable or liquefiable solids are classified as.|à¤œà¤²à¤¨à¤¯ à¤¯à¤¾ à¤ªà¤¿à¤˜à¤²à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ à¤ à¥‹à¤¸ à¤•à¥‹ à¤•à¥ˆà¤¸à¥‡ à¤µà¤°à¥à¤—à¥€à¤•à¥ƒà¤¤ à¤•à¤¿à¤¯à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆà¥¤",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "5",
        "question": "Which is the immediate life-saving procedure?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤¤à¤¤à¥à¤•à¤¾à¤² à¤œà¥€à¤µà¤¨ à¤°à¤•à¥à¤·à¤¾ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "First Aid|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤°",
        "option2": "Call a doctor|à¤¡à¥‰à¤•à¥à¤Ÿà¤° à¤•à¥‹ à¤¬à¥à¤²à¤¾à¤à¤‚",
        "option3": "Intensive care|à¤†à¤‚à¤¤à¤°à¤¿à¤• à¤¦à¥‡à¤–à¤­à¤¾à¤²",
        "option4": "Medical treatment|à¤šà¤¿à¤•à¤¿à¤¤à¥à¤¸à¤¾ à¤‰à¤ªà¤šà¤¾à¤°",
        "correct_option": "First Aid|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤°",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/002.jpg"
    },

    {
        "id": "6",
        "question": "What is the class of fire caused by firewood, paper, cloth?|à¤†à¤— à¤•à¤¾ à¤•à¥à¤²à¤¾à¤¸ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ à¤œà¤¿à¤¸à¤•à¥€ à¤µà¤œà¤¹ à¤¸à¥‡ à¤²à¤•à¤¡à¤¼à¥€, à¤•à¤¾à¤—à¤œ, à¤•à¤ªà¤¡à¤¼à¤¾ à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module II",
        "image": 0
    },
    {
        "id": "7",
        "question": "Which fire extinguisher is filled with carbon tetra chloride and bromochlorodifluoromethane (BCF)?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤…à¤—à¥à¤¨à¤¿à¤¶à¤¾à¤®à¤• à¤¬à¤¨à¥à¤¦à¥‚à¤• à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤Ÿà¥‡à¤Ÿà¥à¤°à¤¾ à¤•à¥à¤²à¥‹à¤°à¤¾à¤‡à¤¡ à¤”à¤° à¤¬à¥à¤°à¥‹à¤®à¥‹à¤•à¥à¤²à¥‹à¤°à¥‹à¤¡à¥€à¤«à¥à¤²à¥‹à¤°à¥‹à¤®à¥‡à¤¥à¥‡à¤¨ (à¤¬à¥€à¤¸à¥€à¤à¤«) à¤¸à¥‡ à¤­à¤°à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Carbon dioxide|à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤¡à¤¾à¤‡à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡",
        "option2": "Halon extinguisher|à¤¹à¥ˆà¤²à¥‰à¤¨ à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option3": "Foam extinguisher|à¤«à¥‹à¤® à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option4": "Dry powder extinguisher|à¤¸à¥‚à¤–à¤¾ à¤ªà¤¾à¤‰à¤¡à¤° à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module III",
        "image": 0
    }
    {
        "id": "8",
        "question": "Name the mandatory symbol.|à¤…à¤¨à¤¿à¤µà¤¾à¤°à¥à¤¯ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "option2": "Give way|à¤°à¤¾à¤¸à¥à¤¤à¤¾ à¤¦à¥‡à¤‚",
        "option3": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "correct_option": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/002.jpg"
    },
    {
        "id": "9",
        "question": "Name the warning sign.|à¤šà¥‡à¤¤à¤¾à¤µà¤¨à¥€ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "School|à¤¸à¥à¤•à¥‚à¤²",
        "option2": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option3": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Pedestrian crossing|à¤ªà¥ˆà¤¦à¤² à¤ªà¤¾à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¸à¥à¤¥à¤¾à¤¨",
        "correct_option": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "trade": "Fitter",
        "year": "Third Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/005.jpg"
    },
    {
        "id": "10",
        "question": "Which one is personal safety?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤¹à¥ˆ?",
        "option1": "Keep the machine clean|à¤®à¤¶à¥€à¤¨ à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option2": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "option3": "Keep the gangway and floor clean|à¤—à¥ˆà¤‚à¤—à¤µà¥‡ à¤”à¤° à¤«à¥à¤²à¥‹à¤° à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option4": "Keep the tools at their proper place|à¤‰à¤ªà¤•à¤°à¤£à¥‹à¤‚ à¤•à¥‹ à¤‰à¤¨à¤•à¥‡ à¤‰à¤šà¤¿à¤¤ à¤¸à¥à¤¥à¤¾à¤¨ à¤ªà¤° à¤°à¤–à¥‡à¤‚",
        "correct_option": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },

    {
        "id": "11",
        "question": "Flammable or liquefiable solids are classified as.|à¤œà¤²à¤¨à¤¯ à¤¯à¤¾ à¤ªà¤¿à¤˜à¤²à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ à¤ à¥‹à¤¸ à¤•à¥‹ à¤•à¥ˆà¤¸à¥‡ à¤µà¤°à¥à¤—à¥€à¤•à¥ƒà¤¤ à¤•à¤¿à¤¯à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆà¥¤",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "12",
        "question": "Which is the immediate life-saving procedure?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤¤à¤¤à¥à¤•à¤¾à¤² à¤œà¥€à¤µà¤¨ à¤°à¤•à¥à¤·à¤¾ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "First Aid|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤°",
        "option2": "Call a doctor|à¤¡à¥‰à¤•à¥à¤Ÿà¤° à¤•à¥‹ à¤¬à¥à¤²à¤¾à¤à¤‚",
        "option3": "Intensive care|à¤†à¤‚à¤¤à¤°à¤¿à¤• à¤¦à¥‡à¤–à¤­à¤¾à¤²",
        "option4": "Medical treatment|à¤šà¤¿à¤•à¤¿à¤¤à¥à¤¸à¤¾ à¤‰à¤ªà¤šà¤¾à¤°",
        "correct_option": "First Aid|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤°",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },

    {
        "id": "13",
        "question": "What is the class of fire caused by firewood, paper, cloth?|à¤†à¤— à¤•à¤¾ à¤•à¥à¤²à¤¾à¤¸ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ à¤œà¤¿à¤¸à¤•à¥€ à¤µà¤œà¤¹ à¤¸à¥‡ à¤²à¤•à¤¡à¤¼à¥€, à¤•à¤¾à¤—à¤œ, à¤•à¤ªà¤¡à¤¼à¤¾ à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module II",
        "image": 0
    },
    {
        "id": "14",
        "question": "Which fire extinguisher is filled with carbon tetra chloride and bromochlorodifluoromethane (BCF)?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤…à¤—à¥à¤¨à¤¿à¤¶à¤¾à¤®à¤• à¤¬à¤¨à¥à¤¦à¥‚à¤• à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤Ÿà¥‡à¤Ÿà¥à¤°à¤¾ à¤•à¥à¤²à¥‹à¤°à¤¾à¤‡à¤¡ à¤”à¤° à¤¬à¥à¤°à¥‹à¤®à¥‹à¤•à¥à¤²à¥‹à¤°à¥‹à¤¡à¥€à¤«à¥à¤²à¥‹à¤°à¥‹à¤®à¥‡à¤¥à¥‡à¤¨ (à¤¬à¥€à¤¸à¥€à¤à¤«) à¤¸à¥‡ à¤­à¤°à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Carbon dioxide|à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤¡à¤¾à¤‡à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡",
        "option2": "Halon extinguisher|à¤¹à¥ˆà¤²à¥‰à¤¨ à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option3": "Foam extinguisher|à¤«à¥‹à¤® à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option4": "Dry powder extinguisher|à¤¸à¥‚à¤–à¤¾ à¤ªà¤¾à¤‰à¤¡à¤° à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "Second Year",
        "subject": "Trade Theory",
        "chapter": "Module III",
        "image": 0
    }
]
