[
    {
        "id": "1",
        "question": "Which one is personal safety?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤¹à¥ˆ?",
        "option1": "Keep the machine clean|à¤®à¤¶à¥€à¤¨ à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option2": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "option3": "Keep the gangway and floor clean|à¤—à¥ˆà¤‚à¤—à¤µà¥‡ à¤”à¤° à¤«à¥à¤²à¥‹à¤° à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option4": "Keep the tools at their proper place|à¤‰à¤ªà¤•à¤°à¤£à¥‹à¤‚ à¤•à¥‹ à¤‰à¤¨à¤•à¥‡ à¤‰à¤šà¤¿à¤¤ à¤¸à¥à¤¥à¤¾à¤¨ à¤ªà¤° à¤°à¤–à¥‡à¤‚",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "2",
        "question": "Name the mandatory symbol.|à¤…à¤¨à¤¿à¤µà¤¾à¤°à¥à¤¯ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "option2": "Give way|à¤°à¤¾à¤¸à¥à¤¤à¤¾ à¤¦à¥‡à¤‚",
        "option3": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/002.jpg"
    },
    {
        "id": "3",
        "question": "Flammable or liquefiable solids are classified as.|à¤œà¤²à¤¨à¤¯ à¤¯à¤¾ à¤ªà¤¿à¤˜à¤²à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ à¤ à¥‹à¤¸ à¤•à¥‹ à¤•à¥ˆà¤¸à¥‡ à¤µà¤°à¥à¤—à¥€à¤•à¥ƒà¤¤ à¤•à¤¿à¤¯à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆà¥¤",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "4",
        "question": "Which is the immediate life-saving procedure?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤¤à¤¤à¥à¤•à¤¾à¤² à¤œà¥€à¤µà¤¨ à¤°à¤•à¥à¤·à¤¾ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "First Aid|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤°",
        "option2": "Call a doctor|à¤¡à¥‰à¤•à¥à¤Ÿà¤° à¤•à¥‹ à¤¬à¥à¤²à¤¾à¤à¤‚",
        "option3": "Intensive care|à¤†à¤‚à¤¤à¤°à¤¿à¤• à¤¦à¥‡à¤–à¤­à¤¾à¤²",
        "option4": "Medical treatment|à¤šà¤¿à¤•à¤¿à¤¤à¥à¤¸à¤¾ à¤‰à¤ªà¤šà¤¾à¤°",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "5",
        "question": "Name the warning sign.|à¤šà¥‡à¤¤à¤¾à¤µà¤¨à¥€ à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚à¥¤",
        "option1": "School|à¤¸à¥à¤•à¥‚à¤²",
        "option2": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option3": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Pedestrian crossing|à¤ªà¥ˆà¤¦à¤² à¤ªà¤¾à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¸à¥à¤¥à¤¾à¤¨",
        "correct_option": "C",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/005.jpg"
    },
    {
        "id": "6",
        "question": "What is the class of fire caused by firewood, paper, cloth?|à¤†à¤— à¤•à¤¾ à¤•à¥à¤²à¤¾à¤¸ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ à¤œà¤¿à¤¸à¤•à¥€ à¤µà¤œà¤¹ à¤¸à¥‡ à¤²à¤•à¤¡à¤¼à¥€, à¤•à¤¾à¤—à¤œ, à¤•à¤ªà¤¡à¤¼à¤¾ à¤¹à¥‹à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Class A fire|à¤•à¥à¤²à¤¾à¤¸ à¤ à¤†à¤—",
        "option2": "Class B fire|à¤•à¥à¤²à¤¾à¤¸ à¤¬à¥€ à¤†à¤—",
        "option3": "Class C fire|à¤•à¥à¤²à¤¾à¤¸ à¤¸à¥€ à¤†à¤—",
        "option4": "Class D fire|à¤•à¥à¤²à¤¾à¤¸ à¤¡à¥€ à¤†à¤—",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "7",
        "question": "Which fire extinguisher is filled with carbon tetra chloride and bromochlorodifluoromethane (BCF)?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤…à¤—à¥à¤¨à¤¿à¤¶à¤¾à¤®à¤• à¤¬à¤¨à¥à¤¦à¥‚à¤• à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤Ÿà¥‡à¤Ÿà¥à¤°à¤¾ à¤•à¥à¤²à¥‹à¤°à¤¾à¤‡à¤¡ à¤”à¤° à¤¬à¥à¤°à¥‹à¤®à¥‹à¤•à¥à¤²à¥‹à¤°à¥‹à¤¡à¥€à¤«à¥à¤²à¥‹à¤°à¥‹à¤®à¥‡à¤¥à¥‡à¤¨ (à¤¬à¥€à¤¸à¥€à¤à¤«) à¤¸à¥‡ à¤­à¤°à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Carbon dioxide|à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤¡à¤¾à¤‡à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡",
        "option2": "Halon extinguisher|à¤¹à¥ˆà¤²à¥‰à¤¨ à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option3": "Foam extinguisher|à¤«à¥‹à¤® à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option4": "Dry powder extinguisher|à¤¸à¥‚à¤–à¤¾ à¤ªà¤¾à¤‰à¤¡à¤° à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "8",
        "question": "Which comes under mechanical occupational hazards?|à¤¯à¤¾à¤‚à¤¤à¥à¤°à¤¿à¤• à¤ªà¥‡à¤¶à¥‡à¤µà¤° à¤œà¥‹à¤–à¤¿à¤®à¥‹à¤‚ à¤®à¥‡à¤‚ à¤•à¥à¤¯à¤¾ à¤†à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Noise|à¤§à¥à¤µà¤¨à¤¿",
        "option2": "Toxic|à¤œà¤¹à¤°à¥€à¤²à¤¾",
        "option3": "Unskilled|à¤…à¤¨à¥à¤­à¤¾à¤—à¥€à¤¯",
        "option4": "Unguarded machinery|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤ à¤®à¤¶à¥€à¤¨à¤°à¥€",
        "correct_option": "D",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "9",
        "question": "How to stop the bleeding of an injured person?|à¤à¤• à¤˜à¤¾à¤¯à¤² à¤µà¥à¤¯à¤•à¥à¤¤à¤¿ à¤•à¥€ à¤°à¤•à¥à¤¤à¤¸à¥à¤°à¤¾à¤µ à¤•à¥‹ à¤•à¥ˆà¤¸à¥‡ à¤°à¥‹à¤•à¥‡à¤‚?",
        "option1": "Tie bandage|à¤¬à¥ˆà¤‚à¤¡à¥‡à¤œ à¤¬à¤¾à¤‚à¤§à¥‡à¤‚",
        "option2": "Apply ointment|à¤®à¤²à¤¹à¤® à¤²à¤—à¤¾à¤à¤‚",
        "option3": "Apply tincture over the wound|à¤˜à¤¾à¤µ à¤ªà¤° à¤Ÿà¤¿à¤‚à¤šà¤° à¤²à¤—à¤¾à¤à¤‚",
        "option4": "Apply pressure over the wound|à¤˜à¤¾à¤µ à¤ªà¤° à¤¦à¤¬à¤¾à¤µ à¤¡à¤¾à¤²à¥‡à¤‚",
        "correct_option": "D",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "10",
        "question": "What is the name of the sign?|à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¤¾ à¤¨à¤¾à¤® à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "School|à¤¸à¥à¤•à¥‚à¤²",
        "option2": "Guarded|à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option3": "Unguarded|à¤…à¤¸à¤‚à¤°à¤•à¥à¤·à¤¿à¤¤",
        "option4": "Pedestrian crossing|à¤ªà¥ˆà¤¦à¤² à¤ªà¤¾à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¸à¥à¤¥à¤¾à¤¨",
        "correct_option": "D",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/010.jpg"
    },
    {
        "id": "11",
        "question": "What are the three factors causing fire?|à¤†à¤— à¤•à¤¾ à¤•à¤¾à¤°à¤£ à¤¬à¤¨à¤¨à¥‡ à¤µà¤¾à¤²à¥‡ à¤¤à¥€à¤¨ à¤•à¤¾à¤°à¤• à¤•à¥à¤¯à¤¾ à¤¹à¥ˆà¤‚?",
        "option1": "Fuel, Heat, Oxygen|à¤ˆà¤‚à¤§à¤¨, à¤‰à¤·à¥à¤®à¤¾, à¤‘à¤•à¥à¤¸à¥€à¤œà¤¨",
        "option2": "Oxygen, Fuel, Nitrogen|à¤‘à¤•à¥à¤¸à¥€à¤œà¤¨, à¤ˆà¤‚à¤§à¤¨, à¤¨à¤¾à¤‡à¤Ÿà¥à¤°à¥‹à¤œà¤¨",
        "option3": "Heat, Nitrogen, Oxygen|à¤‰à¤·à¥à¤®à¤¾, à¤¨à¤¾à¤‡à¤Ÿà¥à¤°à¥‹à¤œà¤¨, à¤‘à¤•à¥à¤¸à¥€à¤œà¤¨",
        "option4": "Fuel, Carbon-dioxide, Heat|à¤ˆà¤‚à¤§à¤¨, à¤•à¤¾à¤°à¥à¤¬à¤¨-à¤¡à¤¾à¤‡à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡, à¤‰à¤·à¥à¤®à¤¾",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "12",
        "question": "What is the period referred to as golden hours?|à¤¸à¥à¤µà¤°à¥à¤£à¤¿à¤® à¤˜à¤‚à¤Ÿà¥‡ à¤•à¥‡ à¤°à¥‚à¤ª à¤®à¥‡à¤‚ à¤•à¥Œà¤¨ à¤¸à¤¾ à¤…à¤µà¤§à¤¿ à¤•à¤¹à¤¾ à¤œà¤¾à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "First 30 minutes after the incident|à¤˜à¤Ÿà¤¨à¤¾ à¤•à¥‡ à¤¬à¤¾à¤¦ à¤ªà¤¹à¤²à¥‡ 30 à¤®à¤¿à¤¨à¤Ÿ",
        "option2": "First 30 minutes|à¤ªà¤¹à¤²à¥‡ 30 à¤®à¤¿à¤¨à¤Ÿ",
        "option3": "First 45 minutes of admission|à¤ªà¥à¤°à¤µà¥‡à¤¶ à¤•à¥‡ à¤ªà¤¹à¤²à¥‡ 45 à¤®à¤¿à¤¨à¤Ÿ",
        "option4": "First 60 minutes after treatment|à¤‰à¤ªà¤šà¤¾à¤° à¤•à¥‡ à¤¬à¤¾à¤¦ à¤ªà¤¹à¤²à¥‡ 60 à¤®à¤¿à¤¨à¤Ÿ",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "13",
        "question": "What is the first step in avoiding an accident in the workplace?|à¤•à¤¾à¤°à¥à¤¯à¤¸à¥à¤¥à¤² à¤®à¥‡à¤‚ à¤¹à¤¾à¤¦à¤¸à¥‡ à¤¸à¥‡ à¤¬à¤šà¤¨à¥‡ à¤•à¤¾ à¤ªà¤¹à¤²à¤¾ à¤•à¤¦à¤® à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "By wearing safety equipment|à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤‰à¤ªà¤•à¤°à¤£ à¤ªà¤¹à¤¨à¤•à¤°",
        "option2": "Doing things in one's own way|à¤…à¤ªà¤¨à¥€ à¤®à¤°à¥à¤œà¥€ à¤¸à¥‡ à¤•à¤¾à¤® à¤•à¤°à¤¨à¤¾",
        "option3": "By observing safety precautions|à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤¸à¤¾à¤µà¤§à¤¾à¤¨à¤¿à¤¯à¤¾à¤ à¤§à¥à¤¯à¤¾à¤¨ à¤¸à¥‡ à¤¦à¥‡à¤–à¤•à¤°",
        "option4": "Doing things with a highly skilled working practice|à¤à¤• à¤‰à¤šà¥à¤š à¤•à¥à¤¶à¤² à¤•à¤¾à¤°à¥à¤¯ à¤ªà¥à¤°à¤µà¥ƒà¤¤à¥à¤¤à¤¿ à¤•à¥‡ à¤¸à¤¾à¤¥",
        "correct_option": "C",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "14",
        "question": "What does the symbol denote?|à¤ªà¥à¤°à¤¤à¥€à¤• à¤•à¥à¤¯à¤¾ à¤¸à¥‚à¤šà¤¿à¤¤ à¤•à¤°à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Stop|à¤°à¥à¤•à¥‡à¤‚",
        "option2": "Give way|à¤°à¤¾à¤¸à¥à¤¤à¤¾ à¤¦à¥‡à¤‚",
        "option3": "Pedestrian crossing|à¤ªà¥ˆà¤¦à¤² à¤ªà¤¾à¤° à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤¸à¥à¤¥à¤¾à¤¨",
        "option4": "Overtaking prohibited|à¤“à¤µà¤°à¤Ÿà¥‡à¤•à¤¿à¤‚à¤— à¤®à¤¨à¤¾ à¤¹à¥ˆ",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/014.jpg"
    },
    {
        "id": "15",
        "question": "What is the color code of bins for waste paper segregation?|à¤•à¤šà¤°à¥‡ à¤•à¥‡ à¤ªà¥‡à¤ªà¤° à¤µà¤¿à¤­à¤¾à¤œà¤¨ à¤•à¥‡ à¤²à¤¿à¤ à¤¬à¤¿à¤¨ à¤•à¤¾ à¤°à¤‚à¤— à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "Red|à¤²à¤¾à¤²",
        "option2": "Blue|à¤¨à¥€à¤²à¤¾",
        "option3": "Black|à¤•à¤¾à¤²à¤¾",
        "option4": "Green|à¤¹à¤°à¤¾",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "16",
        "question": "What is the kind of road sign?|à¤¸à¤¡à¤¼à¤• à¤•à¥‡ à¤¸à¤¾à¤‡à¤¨ à¤•à¤¿à¤¸ à¤ªà¥à¤°à¤•à¤¾à¤° à¤•à¥‡ à¤¹à¥‹à¤¤à¥‡ à¤¹à¥ˆà¤‚?",
        "option1": "Police signal|à¤ªà¥à¤²à¤¿à¤¸ à¤¸à¤¿à¤—à¥à¤¨à¤²",
        "option2": "Cautionary sign|à¤¸à¤¾à¤µà¤§à¤¾à¤¨à¥€ à¤¸à¤¾à¤‡à¤¨",
        "option3": "Mandatory sign|à¤…à¤¨à¤¿à¤µà¤¾à¤°à¥à¤¯ à¤¸à¤¾à¤‡à¤¨",
        "option4": "Information sign|à¤¸à¥‚à¤šà¤¨à¤¾ à¤¸à¤¾à¤‡à¤¨",
        "correct_option": "D",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/016.jpg"
    },
    {
        "id": "17",
        "question": "Which fire extinguisher is used for flammable and running liquid fire?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤…à¤—à¥à¤¨à¤¿à¤¶à¤¾à¤®à¤• à¤‰à¤œà¥à¤œà¥à¤µà¤² à¤”à¤° à¤¦à¥à¤°à¤µà¤®à¤¯ à¤†à¤— à¤•à¥‡ à¤²à¤¿à¤ à¤‰à¤ªà¤¯à¥à¤•à¥à¤¤ à¤¹à¥ˆ?",
        "option1": "Foam extinguisher|à¤«à¥‹à¤® à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option2": "Halon extinguisher|à¤¹à¥ˆà¤²à¥‰à¤¨ à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option3": "Dry powder extinguisher|à¤¸à¥‚à¤–à¤¾ à¤ªà¤¾à¤‰à¤¡à¤° à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "option4": "Carbon dioxide (CO2) extinguisher|à¤•à¤¾à¤°à¥à¤¬à¤¨ à¤¡à¤¾à¤‡à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡ (à¤¸à¥€à¤“ 2 ) à¤à¤•à¥à¤¸à¤Ÿà¤¿à¤‚à¤—à¥à¤µà¤¿à¤¶à¤°",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "18",
        "question": "What A denotes in ABC of first aid?|à¤ªà¥à¤°à¤¾à¤¥à¤®à¤¿à¤• à¤‰à¤ªà¤šà¤¾à¤° à¤•à¥‡ ABC à¤®à¥‡à¤‚ A à¤•à¤¾ à¤•à¥à¤¯à¤¾ à¤¸à¥‚à¤šà¤¿à¤¤ à¤•à¤°à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Airway|à¤µà¤¾à¤¯à¥à¤®à¤¾à¤°à¥à¤—",
        "option2": "Attention|à¤§à¥à¤¯à¤¾à¤¨",
        "option3": "Arresting|à¤…à¤°à¥‡à¤¸à¥à¤Ÿà¤¿à¤‚à¤—",
        "option4": "Atmosphere|à¤µà¤¾à¤¤à¤¾à¤µà¤°à¤£",
        "correct_option": "A",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "19",
        "question": "What is the process of breaking down the materials into organic compounds and can be used as manure?|à¤¸à¤¾à¤®à¤—à¥à¤°à¤¿à¤¯à¥‹à¤‚ à¤•à¥‹ à¤œà¥ˆà¤µ à¤¯à¥Œà¤—à¤¿à¤•à¥‹à¤‚ à¤®à¥‡à¤‚ à¤µà¤¿à¤­à¤¾à¤œà¤¿à¤¤ à¤•à¤°à¤¨à¥‡ à¤”à¤° à¤–à¤¾à¤¦ à¤•à¥‡ à¤°à¥‚à¤ª à¤®à¥‡à¤‚ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¤¨à¥‡ à¤•à¤¾ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "Landfills|à¤²à¥ˆà¤‚à¤¡à¤«à¤¿à¤²à¥à¤¸",
        "option2": "Composting|à¤•à¤®à¥à¤ªà¥‹à¤¸à¥à¤Ÿà¤¿à¤‚à¤—",
        "option3": "Recycling|à¤°à¥€à¤¸à¤¾à¤‡à¤•à¥à¤²à¤¿à¤‚à¤—",
        "option4": "Incineration|à¤‡à¤‚à¤¸à¤¿à¤¨à¤°à¥‡à¤¶à¤¨",
        "correct_option": "B",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "20",
        "question": "What is the colour code for plastic waste bin? | à¤ªà¥à¤²à¤¾à¤¸à¥à¤Ÿà¤¿à¤• à¤•à¤šà¤°à¤¾ à¤¬à¤¿à¤¨ à¤•à¥‡ à¤²à¤¿à¤ à¤•à¤²à¤° à¤•à¥‹à¤¡ à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "Red | à¤²à¤¾à¤²",
        "option2": "Blue | à¤¨à¥€à¤²à¤¾",
        "option3": "Green | à¤¹à¤°à¤¾",
        "option4": "Yellow | à¤ªà¥€à¤²à¤¾",
        "correct_option": "D",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "21",
        "question": "Name the part of file marked as x. | à¤«à¤¾à¤‡à¤² à¤•à¥‡ à¤‰à¤¸ à¤¹à¤¿à¤¸à¥à¤¸à¥‡ à¤•à¤¾ à¤¨à¤¾à¤® à¤¬à¤¤à¤¾à¤à¤‚ à¤œà¤¿à¤¸à¥‡ x à¤•à¥‡ à¤°à¥‚à¤ª à¤®à¥‡à¤‚ à¤šà¤¿à¤¹à¥à¤¨à¤¿à¤¤ à¤•à¤¿à¤¯à¤¾ à¤—à¤¯à¤¾ à¤¹à¥ˆà¥¤",
        "option1": "Face | à¤«à¥‡à¤¸",
        "option2": "Pein | à¤ªà¥€à¤¨ à¤ªà¥ˆà¤¨",
        "option3": "Cheek | à¤šà¥€à¤•",
        "option4": "Eye hole | à¤†à¤ˆ à¤¹à¥‹à¤²",
        "correct_option": "C",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": "https:\/\/icf.gov.in\/quiz\/images\/021.jpg"
    },
    {
        "id": "22",
        "question": "What is the use of a try square? | à¤à¤• à¤Ÿà¥à¤°à¤¾à¤ˆ à¤¸à¥à¤•à¥à¤µà¥‡à¤¯à¤° à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¥à¤¯à¤¾ à¤¹à¥ˆ?",
        "option1": "To check right angle | à¤¸à¤®à¤•à¥‹à¤£ à¤•à¥€ à¤œà¤¾à¤à¤š à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤",
        "option2": "To check acute angle | à¤¨à¥à¤¯à¥‚à¤¨à¤¤à¤® à¤•à¥‹à¤£ à¤•à¥€ à¤œà¤¾à¤à¤š à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤",
        "option3": "To check obtuse angle | à¤µà¤¿à¤·à¤® à¤•à¥‹à¤£ à¤•à¥€ à¤œà¤¾à¤à¤š à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤",
        "option4": "To check straight angle | à¤¸à¥€à¤§à¥‡ à¤•à¥‹à¤£ à¤•à¥€ à¤œà¤¾à¤à¤š à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤",
        "correct_option": "T",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "23",
        "question": "Which marking media is poisonous? | à¤•à¥Œà¤¨ à¤¸à¤¾ à¤®à¤¾à¤°à¥à¤•à¤¿à¤‚à¤— à¤®à¥€à¤¡à¤¿à¤¯à¤¾ à¤œà¤¹à¤°à¥€à¤²à¤¾ à¤¹à¥ˆ?",
        "option1": "White wash | à¤µà¥à¤¹à¤¾à¤‡à¤Ÿ à¤µà¥‰à¤¶",
        "option2": "Prussian blue | à¤ªà¥à¤°à¤¸à¤¿à¤¯à¤¨ à¤¬à¥à¤²à¥à¤¯à¥‚",
        "option3": "Copper sulphate | à¤•à¥‰à¤ªà¤° à¤¸à¤²à¥à¤«à¥‡à¤Ÿ",
        "option4": "Cellulose lacquer | à¤¸à¥‡à¤²à¥à¤²à¥‹à¤œ à¤²à¥ˆà¤•à¤°",
        "correct_option": "C",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "24",
        "question": "Which part of universal surface gauge holds the scriber? | à¤¯à¥‚à¤¨à¤¿à¤µà¤°à¥à¤¸à¤² à¤¸à¤°à¤«à¥‡à¤¸ à¤—à¥‡à¤œ à¤•à¤¾ à¤•à¥Œà¤¨ à¤¸à¤¾ à¤¹à¤¿à¤¸à¥à¤¸à¤¾ à¤¸à¥à¤•à¥à¤°à¤¾à¤‡à¤¬à¤° à¤•à¥‹ à¤ªà¤•à¤¡à¤¼à¤¤à¤¾ à¤¹à¥ˆ?",
        "option1": "Snug | à¤¸à¥à¤¨à¤—",
        "option2": "Guide pin | à¤—à¤¾à¤‡à¤¡ à¤ªà¤¿à¤¨",
        "option3": "Rocker arm | à¤°à¥‰à¤•à¤° à¤†à¤°à¥à¤®",
        "option4": "Fine adjustment screw | à¤«à¤¾à¤‡à¤¨ à¤à¤¡à¤œà¤¸à¥à¤Ÿà¤®à¥‡à¤‚à¤Ÿ à¤¸à¥à¤•à¥à¤°à¥‚",
        "correct_option": "S",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "25",
        "question": "A new hacksaw blade after a few strokes becomes loose because of? | à¤•à¥à¤› à¤¸à¥à¤Ÿà¥à¤°à¥‹à¤• à¤•à¥‡ à¤¬à¤¾à¤¦ à¤à¤• à¤¨à¤ˆ à¤¹à¥ˆà¤•à¥à¤¸à¥‰ à¤¬à¥à¤²à¥‡à¤¡ à¤¢à¥€à¤²à¥€ à¤¹à¥‹ à¤œà¤¾à¤¤à¥€ à¤¹à¥ˆ à¤•à¥à¤¯à¥‹à¤‚à¤•à¤¿?",
        "option1": "Stretching of blade | à¤¬à¥à¤²à¥‡à¤¡ à¤•à¥€ à¤–à¥€à¤‚à¤š",
        "option2": "Wrong pitch of the blade | à¤¬à¥à¤²à¥‡à¤¡ à¤•à¤¾ à¤—à¤²à¤¤ à¤ªà¤¿à¤š",
        "option3": "Improper selection of saw sets | à¤–à¤°à¤¾à¤¬ à¤¸à¥‰ à¤¸à¥‡à¤Ÿ à¤•à¤¾ à¤šà¤¯à¤¨",
        "option4": "Nut thread being worn out | à¤¨à¤Ÿ à¤¥à¥à¤°à¥‡à¤¡ à¤•à¥€ à¤˜à¤¿à¤¸ à¤œà¤¾à¤¨à¤¾",
        "correct_option": "S",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "26",
        "question": "Why does the breakage of teeth occur easily while sawing thin-walled workpieces at the start of the cut? | à¤•à¤Ÿà¤¿à¤‚à¤— à¤•à¥‡ à¤ªà¥à¤°à¤¾à¤°à¤‚à¤­ à¤®à¥‡à¤‚ à¤ªà¤¤à¤²à¥€ à¤¦à¥€à¤µà¤¾à¤°à¥‹à¤‚ à¤µà¤¾à¤²à¥‡ à¤•à¤¾à¤®à¤ªà¥€à¤¸ à¤•à¥‹ à¤†à¤¸à¤¾à¤¨à¥€ à¤¸à¥‡ à¤¦à¤¾à¤‚à¤¤ à¤Ÿà¥‚à¤Ÿ à¤œà¤¾à¤¤à¥‡ à¤¹à¥ˆà¤‚ à¤•à¥à¤¯à¥‹à¤‚à¤•à¤¿?",
        "option1": "Hand force is too big | à¤¹à¥ˆà¤‚à¤¡ à¤«à¥‹à¤°à¥à¤¸ à¤¬à¤¹à¥à¤¤ à¤¬à¤¡à¤¼à¥€ à¤¹à¥ˆ",
        "option2": "Cutting section is too short | à¤•à¤Ÿà¤¿à¤‚à¤— à¤¸à¥‡à¤•à¥à¤¶à¤¨ à¤¬à¤¹à¥à¤¤ à¤›à¥‹à¤Ÿà¥€ à¤¹à¥ˆ",
        "option3": "Coarse blade to be used | à¤•à¥‹à¤°à¥à¤¸ à¤¬à¥à¤²à¥‡à¤¡ à¤•à¤¾ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¤¨à¤¾",
        "option4": "Hand force acts only upon few teeth | à¤¹à¥ˆà¤‚à¤¡ à¤«à¥‹à¤°à¥à¤¸ à¤•à¥‡à¤µà¤² à¤•à¥à¤› à¤¦à¤¾à¤‚à¤¤à¥‹à¤‚ à¤ªà¤° à¤•à¤¾à¤°à¥à¤¯ à¤•à¤°à¤¤à¥€ à¤¹à¥ˆ",
        "correct_option": "H",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "27",
        "question": "Which paint dries faster? | à¤•à¥Œà¤¨ à¤¸à¥€ à¤ªà¥‡à¤‚à¤Ÿ à¤œà¤²à¥à¤¦à¥€ à¤¸à¥‡ à¤¸à¥à¤–à¤¤à¥€ à¤¹à¥ˆ?",
        "option1": "Oil paint | à¤‘à¤¯à¤² à¤ªà¥‡à¤‚à¤Ÿ",
        "option2": "Synthetic enamel | à¤¸à¤¿à¤‚à¤¥à¥‡à¤Ÿà¤¿à¤• à¤à¤¨à¤¾à¤®à¥‡à¤²",
        "option3": "Lime paint | à¤šà¥‚à¤¨à¥‡ à¤•à¤¾ à¤ªà¥‡à¤‚à¤Ÿ",
        "option4": "Zinc oxide paint | à¤œà¤¿à¤‚à¤• à¤‘à¤•à¥à¤¸à¤¾à¤‡à¤¡ à¤ªà¥‡à¤‚à¤Ÿ",
        "correct_option": "S",
        "trade": "Fitter",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
    {
        "id": "28",
        "question": "Which one is personal safety?|à¤•à¥Œà¤¨ à¤¸à¤¾ à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤¹à¥ˆ?",
        "option1": "Keep the machine clean|à¤®à¤¶à¥€à¤¨ à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option2": "Concentrate on your work|à¤…à¤ªà¤¨à¥‡ à¤•à¤¾à¤® à¤ªà¤° à¤§à¥à¤¯à¤¾à¤¨ à¤•à¥‡à¤‚à¤¦à¥à¤°à¤¿à¤¤ à¤•à¤°à¥‡à¤‚",
        "option3": "Keep the gangway and floor clean|à¤—à¥ˆà¤‚à¤—à¤µà¥‡ à¤”à¤° à¤«à¥à¤²à¥‹à¤° à¤•à¥‹ à¤¸à¤¾à¤« à¤°à¤–à¥‡à¤‚",
        "option4": "Keep the tools at their proper place|à¤‰à¤ªà¤•à¤°à¤£à¥‹à¤‚ à¤•à¥‹ à¤‰à¤¨à¤•à¥‡ à¤‰à¤šà¤¿à¤¤ à¤¸à¥à¤¥à¤¾à¤¨ à¤ªà¤° à¤°à¤–à¥‡à¤‚",
        "correct_option": "B",
        "trade": "Plumber",
        "year": "First Year",
        "subject": "Trade Theory",
        "chapter": "Module I",
        "image": 0
    },
]
